import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import WordGrid from '../components/WordGrid'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <WordGrid />
        <ol style={{color:"white"}}>
          <li>Type in your guessed words</li>
          <li>Click on the letters to cycle through Absent/Present/Correct</li>
        </ol>
      </main>
    </div>
  )
}

export default Home
